[package]
name = "embedded_task_dispatcher"
version = "0.1.0"
edition = "2021"

[dependencies]
custom_error = "1.9.2"
rppal = "0.19.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
